name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run Black
        run: |
          black .
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Commit and push if needed
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'github-action@users.noreply.github.com'
          git commit -am "Automated code formatting"
          git push
